# -- Configurazione Ingressi Digitali (8 Digital Inputs) --
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 1"
    id: input_1
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 2"
    id: input_2
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 3"
    id: input_3
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 4"
    id: input_4
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 5"
    id: input_5
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 6"
    id: input_6
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 7"
    id: input_7
    device_class: opening

  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
    name: "Ingresso Digitale 8"
    id: input_8
    device_class: opening

  # Pulsante di BOOT
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Pulsante Boot"
    id: boot_button
