# -- Configurazione orario --
time:
  - platform: pcf85063
    update_interval: never
  - platform: homeassistant
    id: ha_time
    timezone: "Europe/Rome"
    on_time_sync:
      then:
        pcf85063.write_time:

# -- Intervalli di controllo --
interval:
  # Log dell'ora corrente ogni minuto
  - interval: 60s
    then:
      - lambda: |-
          auto t_ha = id(ha_time).now();
         
          if (t_ha.is_valid()) {
            ESP_LOGD("clock", "Ora HA: %s", t_ha.strftime("%Y-%m-%d %H:%M:%S").c_str());
          } else {
            ESP_LOGW("clock", "Ora HA non valida");
          }
