substitutions:
  device_name: "esp32-solaio"
  friendly_name: "Esp32-Solaio"
  device_description: "VMC Sabiana ENY-SP-180"

  logger: "INFO"  # Livello di log globale (DEBUG, VERBOSE, INFO, WARN, ERROR)

  modbus_address: "0x01"  # Indirizzo della VMC (solo pin 1 su ON)